# Generated by Django 3.2.9 on 2021-12-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='QuartersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2021/2022', max_length=255)),
                ('title', models.CharField(choices=[('1-chorak', '1-chorak'), ('2-chorak', '2-chorak'), ('3-chorak', '3-chorak'), ('4-chorak', '4-chorak')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chorak',
                'verbose_name_plural': 'chorak',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbschool.classesmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.schoolmodel')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'talabalar',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mavzu',
                'verbose_name_plural': 'mavzular',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.schoolmodel')),
                ('subject', models.ManyToManyField(to='dbschool.SubjectModel')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='TakesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbschool.studentmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbschool.subjectmodel')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=100)),
                ('hour', models.CharField(choices=[(1, '1-dars'), (2, '2-dars'), (3, '3-dars'), (4, '4-dars'), (5, '5-dars'), (6, '6-dars')], max_length=100)),
                ('quarter', models.ManyToManyField(to='dbschool.QuartersModel')),
                ('schclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbschool.classesmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.schoolmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbschool.subjectmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbschool.teachermodel')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
            },
        ),
    ]
