# Generated by Django 3.2.9 on 2021-12-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': 'fan', 'verbose_name_plural': 'fanlar'},
        ),
    ]
