# Generated by Django 3.2.9 on 2021-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschool', '0002_alter_subjectmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='ball',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
