# Generated by Django 3.2.9 on 2021-12-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbschool', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('classes', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dbschool.classesmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.schoolmodel')),
            ],
            options={
                'verbose_name': 'Kurator',
                'verbose_name_plural': 'kuratorlar',
            },
        ),
        migrations.CreateModel(
            name='DirektorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.schoolmodel')),
            ],
            options={
                'verbose_name': 'direktor',
                'verbose_name_plural': 'direktorlar',
            },
        ),
    ]
